/* Generated By:JavaCC: Do not edit this line. NewAdderConstants.java */
package NewAdder;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NewAdderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int VARIABLE = 8;
  /** RegularExpression Id. */
  int NUMMER = 9;
  /** RegularExpression Id. */
  int DIGITS = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int PLUS = 12;
  /** RegularExpression Id. */
  int MINUS = 13;
  /** RegularExpression Id. */
  int MULIPIKATION = 14;
  /** RegularExpression Id. */
  int DIVISION = 15;
  /** RegularExpression Id. */
  int EQUEAL = 16;
  /** RegularExpression Id. */
  int LMPRANRENT = 17;
  /** RegularExpression Id. */
  int RMPRANRENT = 18;
  /** RegularExpression Id. */
  int OPEN_PAR = 19;
  /** RegularExpression Id. */
  int CLOSE_PAR = 20;
  /** RegularExpression Id. */
  int LBRACE = 21;
  /** RegularExpression Id. */
  int RBRACE = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int GROSS = 25;
  /** RegularExpression Id. */
  int GROSS_GLEICH = 26;
  /** RegularExpression Id. */
  int KLEIN = 27;
  /** RegularExpression Id. */
  int KLEIN_GLEICH = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int NOT = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"int\"",
    "\"if\"",
    "<VARIABLE>",
    "<NUMMER>",
    "<DIGITS>",
    "<STRING>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\">\"",
    "\"=>\"",
    "\"<\"",
    "\"<=\"",
    "<AND>",
    "<OR>",
    "<NOT>",
  };

}
