/* Generated By:JavaCC: Do not edit this line. NewAdderConstants.java */
package NewAdder;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NewAdderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 3;
  /** RegularExpression Id. */
  int IF = 4;
  /** RegularExpression Id. */
  int STRING = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int MULIPIKATION = 9;
  /** RegularExpression Id. */
  int DIVISION = 10;
  /** RegularExpression Id. */
  int EQUEAL = 11;
  /** RegularExpression Id. */
  int LPRANRENT = 12;
  /** RegularExpression Id. */
  int RPRANRENT = 13;
  /** RegularExpression Id. */
  int LMPRANRENT = 14;
  /** RegularExpression Id. */
  int RMPRANRENT = 15;
  /** RegularExpression Id. */
  int LBIGPRANRENT = 16;
  /** RegularExpression Id. */
  int RBIGPRANRENT = 17;
  /** RegularExpression Id. */
  int COLON = 18;
  /** RegularExpression Id. */
  int COMMA = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"int\"",
    "\"if\"",
    "<STRING>",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
  };

}
