/* Generated By:JavaCC: Do not edit this line. NewAdderConstants.java */
package NewAdder;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NewAdderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int INT = 3;
  /** RegularExpression Id. */
  int IF = 4;
  /** RegularExpression Id. */
  int STRING = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int DIGITS = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int MULIPIKATION = 10;
  /** RegularExpression Id. */
  int DIVISION = 11;
  /** RegularExpression Id. */
  int EQUEAL = 12;
  /** RegularExpression Id. */
  int LMPRANRENT = 13;
  /** RegularExpression Id. */
  int RMPRANRENT = 14;
  /** RegularExpression Id. */
  int LPAR = 15;
  /** RegularExpression Id. */
  int RPAR = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int OPEN_PAR = 19;
  /** RegularExpression Id. */
  int CLOSE_PAR = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\"int\"",
    "\"if\"",
    "<STRING>",
    "<NUMBER>",
    "<DIGITS>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
